# Generated by Django 5.2.4 on 2025-07-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('gdg_member', 'GDG Member'), ('event_head', 'Event Head'), ('hod', 'HOD'), ('teacher', 'Teacher'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
