# Generated by Django 5.2.4 on 2025-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('is_approved_by_hod', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('systems_required', models.TextField(blank=True, help_text='List any systems: mic, speakers, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved_by_event_head', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
    ]
