# Generated by Django 5.2.4 on 2025-07-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_approved_by_hod',
            new_name='is_venue_approved_by_hod',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tech_talk', 'Tech Talk'), ('workshop', 'Workshop'), ('competition', 'Competition'), ('meetup', 'Meetup'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='systems_required',
            field=models.TextField(blank=True, help_text='List any systems: mic, speakers, projector, etc.'),
        ),
    ]
