# Generated by Django 5.2.4 on 2025-07-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_is_approved_by_hod_event_is_venue_approved_by_hod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_date_to_apply',
            field=models.DateField(default='2025-07-10', help_text='Last date to register for the event'),
            preserve_default=False,
        ),
    ]
