# Generated by Django 5.2.4 on 2025-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_last_date_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Optional external registration link (Google Form, etc.)', max_length=300, null=True),
        ),
    ]
