# Generated by Django 5.2.4 on 2025-07-12 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_registration_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speaker',
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_gdg_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'GDG'}, related_name='assigned_events_as_gdg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Teacher'}, related_name='assigned_events_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_head',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EventHead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_venue_approval', 'Pending Venue Approval'), ('venue_approved', 'Venue Approved'), ('published', 'Published'), ('completed', 'Completed'), ('attendance_sent_to_erp', 'Attendance Sent to ERP')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_attendance_approved_by_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_date_to_apply',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='systems_required',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GDGTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'GDG'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
