# Generated by Django 5.2.4 on 2025-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('events_led', models.IntegerField(default=0)),
                ('issues_reported', models.IntegerField(default=0)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
