# Generated by Django 5.2.4 on 2025-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_by_student', models.BooleanField(default=False)),
                ('approved_by_event_head', models.BooleanField(default=False)),
                ('approved_by_hod', models.BooleanField(default=False)),
                ('finalized_for_erp', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
