# Generated by Django 5.2.4 on 2025-07-12 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_initial'),
        ('events', '0004_event_last_date_to_apply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_by_student', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_event_head', models.BooleanField(default=False)),
                ('approved_by_event_head_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_hod', models.BooleanField(default=False)),
                ('approved_by_hod_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_to_erp', models.BooleanField(default=False)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
